groups:
  - name: worktrack_alerts
    rules:
      - alert: WorktrackHighCPU
        # Demo/test alert: this condition is intentionally set
        expr: process_cpu_seconds_total > 0
        for: 10s
        labels:
          severity: warning
        annotations:
          description: "Worktrack app  high CPU usage activity detected."
